import { beforeAll, describe, expect, it } from 'vitest';
import sharp, { type Sharp } from 'sharp';
import { SharpImageProcessor } from '../../src/modules/catalogue/infrastructure/media-processing/sharp-image-processor.js';
import {
  ImageDecodeError,
  type GeneratedVariant,
} from '../../src/modules/catalogue/application/ports/image-processor.port.js';

/**
 * `SharpImageProcessor` against **real libvips** (S2-6b, SDD 12.2 steps 5a–5f).
 *
 * In `test/integration/` rather than `test/unit/` deliberately: the whole
 * point of this suite is that nothing here is faked. Decoding real JPEG and
 * PNG containers, encoding real WebP and AVIF, and proving EXIF/GPS actually
 * leaves the output are facts about the library, not about our code — a mock
 * would assert only that the mock was written to agree with the assertion.
 *
 * Fixtures are generated by Sharp itself at `beforeAll` rather than committed
 * as binaries: it keeps the repository free of opaque blobs, and an image
 * built here is one whose exact dimensions and metadata the assertions can
 * state rather than assume.
 */
describe('SharpImageProcessor (real libvips)', () => {
  const processor = new SharpImageProcessor();

  /** Wider than the largest variant (1600) so every resize step is a genuine downscale. */
  const SOURCE_WIDTH = 2400;
  const SOURCE_HEIGHT = 1200;

  let jpeg: Buffer;
  let jpegWithExif: Buffer;
  let png: Buffer;
  let webp: Buffer;
  let svg: Buffer;
  let garbage: Buffer;
  let tiny: Buffer;

  const canvas = (width: number, height: number): Sharp =>
    sharp({
      create: { width, height, channels: 3, background: { r: 210, g: 120, b: 40 } },
    });

  beforeAll(async () => {
    jpeg = await canvas(SOURCE_WIDTH, SOURCE_HEIGHT).jpeg().toBuffer();

    // libvips numbers the EXIF directories: IFD0 is the main image, IFD3 is
    // the GPS directory. Both are written here so the stripping assertions
    // below have something real to strip — the whole point of the SDD's
    // "STRIP EXIF" step is a photo carrying the location it was taken at.
    jpegWithExif = await sharp(jpeg)
      .withExif({
        IFD0: { Copyright: 'Leen Mart Fixture', Software: 'sharp-image-processor.test' },
        IFD3: { GPSLatitudeRef: 'N', GPSLongitudeRef: 'E' },
      })
      .jpeg()
      .toBuffer();

    png = await canvas(SOURCE_WIDTH, SOURCE_HEIGHT).png().toBuffer();
    webp = await canvas(SOURCE_WIDTH, SOURCE_HEIGHT).webp().toBuffer();
    svg = Buffer.from(
      '<svg xmlns="http://www.w3.org/2000/svg" width="100" height="100"><rect width="100" height="100"/></svg>',
    );
    garbage = Buffer.from('GIF89a-but-then-nothing-that-parses-as-any-image-at-all');
    tiny = await canvas(120, 90).jpeg().toBuffer();
  });

  describe('readMetadata — magic bytes, never the declared type', () => {
    it('reports jpeg for a real JPEG', async () => {
      const metadata = await processor.readMetadata(jpeg);

      expect(metadata.format).toBe('jpeg');
      expect(metadata.width).toBe(SOURCE_WIDTH);
      expect(metadata.height).toBe(SOURCE_HEIGHT);
    });

    it('reports png for a real PNG', async () => {
      expect((await processor.readMetadata(png)).format).toBe('png');
    });

    it('reports webp for a real WebP', async () => {
      expect((await processor.readMetadata(webp)).format).toBe('webp');
    });

    it('reports png for PNG bytes, whatever they were declared as — this is what catches a spoofed content type', async () => {
      // The upload row would say `image/jpeg`; the bytes say otherwise, and
      // `ProcessProductMediaUseCase` turns that disagreement into
      // CONTENT_TYPE_MISMATCH.
      expect((await processor.readMetadata(png)).format).not.toBe('jpeg');
    });

    it('reports svg for an SVG — which is how the caller rejects it', async () => {
      expect((await processor.readMetadata(svg)).format).toBe('svg');
    });

    it('reports svg for an SVG whose extension and declared type both claim JPEG', async () => {
      // The processor is never handed a filename, so there is nothing to be
      // fooled by: the decoder's own answer is the only input.
      expect((await processor.readMetadata(svg)).format).toBe('svg');
    });

    it('throws ImageDecodeError for bytes that are not an image at all', async () => {
      await expect(processor.readMetadata(garbage)).rejects.toBeInstanceOf(ImageDecodeError);
    });

    it('throws ImageDecodeError for a truncated JPEG', async () => {
      await expect(processor.readMetadata(jpeg.subarray(0, 12))).rejects.toBeInstanceOf(
        ImageDecodeError,
      );
    });

    it('throws ImageDecodeError for an empty buffer', async () => {
      await expect(processor.readMetadata(Buffer.alloc(0))).rejects.toBeInstanceOf(
        ImageDecodeError,
      );
    });
  });

  describe('generateVariants — the SDD 12.2 matrix (D-S2-6-F)', () => {
    let variants: readonly GeneratedVariant[];

    beforeAll(async () => {
      variants = await processor.generateVariants(jpegWithExif);
    });

    const find = (width: number, format: string): GeneratedVariant => {
      const found = variants.find((v) => v.width === width && v.format === format);
      if (!found) throw new Error(`no ${width}/${format} variant`);
      return found;
    };

    it('produces exactly eight', () => {
      expect(variants).toHaveLength(8);
    });

    it('produces every (width, format) pair exactly once', () => {
      const pairs = variants.map((v) => `${v.width}:${v.format}`).sort();
      expect(pairs).toEqual(
        [
          '1600:AVIF',
          '1600:WEBP',
          '200:AVIF',
          '200:WEBP',
          '400:AVIF',
          '400:WEBP',
          '800:AVIF',
          '800:WEBP',
        ].sort(),
      );
    });

    it('emits real WebP bytes for every WEBP variant', async () => {
      for (const variant of variants.filter((v) => v.format === 'WEBP')) {
        // four sequential decodes; readability beats parallelism in an assertion.
        expect((await sharp(variant.bytes).metadata()).format).toBe('webp');
      }
    });

    it('emits real AVIF bytes for every AVIF variant', () => {
      for (const variant of variants.filter((v) => v.format === 'AVIF')) {
        // The ISOBMFF brand, read straight from the container header — a more
        // direct fact than Sharp's own `metadata().format`, which reports the
        // generic `heif` for the whole AVIF/HEIC family.
        expect(variant.bytes.subarray(4, 12).toString('latin1')).toBe('ftypavif');
      }
    });

    it.each([200, 400, 800, 1600])(
      'resizes the %i px WebP variant to exactly that width',
      async (width) => {
        expect((await sharp(find(width, 'WEBP').bytes).metadata()).width).toBe(width);
      },
    );

    it.each([200, 400, 800, 1600])(
      'resizes the %i px AVIF variant to exactly that width',
      async (width) => {
        expect((await sharp(find(width, 'AVIF').bytes).metadata()).width).toBe(width);
      },
    );

    it('preserves the aspect ratio rather than distorting', async () => {
      const sourceRatio = SOURCE_WIDTH / SOURCE_HEIGHT;
      for (const width of [200, 400, 800, 1600]) {
        const metadata = await sharp(find(width, 'WEBP').bytes).metadata();
        expect((metadata.width ?? 0) / (metadata.height ?? 1)).toBeCloseTo(sourceRatio, 1);
      }
    });

    it('produces non-empty bytes for every variant', () => {
      for (const variant of variants) {
        expect(variant.bytes.length).toBeGreaterThan(0);
      }
    });

    it('re-encodes rather than copying — no output is byte-identical to the source', () => {
      for (const variant of variants) {
        expect(variant.bytes.equals(jpegWithExif)).toBe(false);
      }
    });

    it('emits no JPEG at all — the original container never survives', async () => {
      for (const variant of variants.filter((v) => v.format === 'WEBP')) {
        expect((await sharp(variant.bytes).metadata()).format).not.toBe('jpeg');
      }
    });
  });

  describe('EXIF/GPS stripping (SDD 12.2 step 5d)', () => {
    it('confirms the fixture really does carry EXIF — otherwise the assertions below are vacuous', async () => {
      const metadata = await sharp(jpegWithExif).metadata();

      expect(metadata.exif).toBeDefined();
      expect(metadata.exif?.toString('latin1')).toContain('Leen Mart Fixture');
    });

    it('leaves no EXIF block on any of the eight outputs', async () => {
      const variants = await processor.generateVariants(jpegWithExif);

      for (const variant of variants) {
        // eight sequential decodes.
        const metadata = await sharp(variant.bytes).metadata();
        expect(metadata.exif).toBeUndefined();
      }
    });

    it('leaves no trace of the GPS directory or the copyright string in the raw output bytes', async () => {
      const variants = await processor.generateVariants(jpegWithExif);

      for (const variant of variants) {
        const raw = variant.bytes.toString('latin1');
        expect(raw).not.toContain('Leen Mart Fixture');
        expect(raw).not.toContain('sharp-image-processor.test');
        expect(raw).not.toContain('GPSLatitude');
      }
    });
  });

  describe('never upscales (D-S2-6-F)', () => {
    it('caps every variant at the source width for a small original', async () => {
      const variants = await processor.generateVariants(tiny);

      for (const variant of variants.filter((v) => v.format === 'WEBP')) {
        // four sequential decodes.
        const metadata = await sharp(variant.bytes).metadata();
        expect(metadata.width).toBeLessThanOrEqual(120);
      }
    });

    it('still produces all eight rows for a small original — a narrow "1600" is a legitimate variant', async () => {
      expect(await processor.generateVariants(tiny)).toHaveLength(8);
    });
  });

  describe('PNG sources', () => {
    it('re-encodes a PNG into the same eight WebP/AVIF outputs', async () => {
      const variants = await processor.generateVariants(png);

      expect(variants).toHaveLength(8);
      expect((await sharp(variants[0]?.bytes ?? Buffer.alloc(0)).metadata()).format).not.toBe(
        'png',
      );
    });
  });

  describe('undecodable input', () => {
    it('rejects rather than emitting variants', async () => {
      await expect(processor.generateVariants(garbage)).rejects.toThrow();
    });
  });
});
